version: '3'

services:
  playground: # Docker Compose 내에서 서비스 이름은 DNS 이름으로 동작
    container_name: playground
    image: playground:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000

  database:
    container_name: database
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mariaDB/data:/var/lib/mysql
      - ./mariaDB/conf.d:/etc/mysql/conf.d
      - ./mariaDB/initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
    env_file: ./src/config/env/.production.env

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/  # 이 경로를 마운트
    depends_on: # 해당 서비스가 시작되기 전에 다른 서비스가 먼저 시작되어야 함을 지정
      - playground
